name: Auto commit

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "15 8 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          curl https://www.thestreet.com/files/r/ratings/equities/TSLA_weiss.pdf\?utm_medium\=triggered\&utm_source\=getreport -o TSLA.pdf
          curl https://www.thestreet.com/files/r/ratings/equities/AAPL_weiss.pdf\?utm_medium\=triggered\&utm_source\=getreport -o AAPL.pdf
          curl https://www.thestreet.com/files/r/ratings/equities/AMZN_weiss.pdf\?utm_medium\=triggered\&utm_source\=getreport -o AMZN.pdf
          
      - name: Commit changes
        run: |
          git config --local user.email "438410248@qq.com"
          git config --local user.name "Ian729"
          git add -A
          
          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
